name: gsheet_to_arb_example
description: Example of how to use ghseet_to_arb plugin

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: any

dev_dependencies:
  gsheet_to_arb: #^0.1.8
    path: ../
  test: any
  mockito: any

gsheet_to_arb:
  arb_file_prefix: ""
  localization_file_name: "l10n"
  output_directory: "lib/l10n"
  generate_code: false
  add_context_prefix: false
  gsheet:
    auth_file: "./pubspec.yaml"
    document_id: "1CwFRjtiCmCl8yvP55yBT70h-Yt00CcigD816hsGo7KU"
    category_prefix: "# "
    sheet_id: 0
